export const LABELS_MR = {
  NAVBAR: {
    HOME: 'मुख्यपृष्ठ',
    AI: 'एआय',
    AI_ASSISTANT: 'एआय सहाय्यक',
    EXPLORE: 'शोधा',
    SAVED: 'सेव्ह केलेले',
    SETTINGS: 'सेटिंग्ज',
    EXPAND_SIDEBAR: 'साइडबार विस्तृत करा',
    COLLAPSE_SIDEBAR: 'साइडबार संकुचित करा',
    SIGN_IN: 'खाते',
    YOU: 'तुम्ही'
  },
  HOME: {
    GREETING: 'शुभ सकाळ,',
    GREETING_MORNING: 'शुभ सकाळ,',
    GREETING_AFTERNOON: 'शुभ दुपार,',
    GREETING_EVENING: 'शुभ संध्याकाळ,',
    WEATHER_HERO_TITLE: 'आजचे हवामान आल्हाददायक आहे.',
    WEATHER_HERO_SUBTITLE: 'स्थानिक कॅफे शोधण्यासाठी उत्तम वेळ.',
    HUMIDITY: 'आर्द्रता',
    GOOD: 'चांगले',
    SUNNY: 'स्वच्छ',
    KM_H: 'किमी/तास',
    WHAT_TO_DO: 'तुम्हाला आज काय करायचे आहे?',
    HINT_COFFEE: '"जवळचे शांत कॉफी शॉप शोधा" वापरून पहा',
    HINT_PARKS: '"जवळचे पार्क दाखवा" वापरून पहा',
    FOR_YOU: 'तुमच्यासाठी',
    RECOMMENDED: 'तुमच्या क्रियाकलापावर आधारित शिफारस',
    PLACES_NEARBY: 'जवळची ठिकाणे',
    NEARBY_HIGHLIGHTS: 'जवळचे मुख्य आकर्षण',
    LOCAL_SPECIALITIES: 'स्थानिक वैशिष्ट्ये',
    NEARBY_SUBTITLE: 'तुमच्या सध्याच्या ठिकाणाभोवतीचे स्पॉट शोधा',
    SWIGGY_INSTAMART: 'स्विगी इन्स्टामार्ट',
    DELIVERY_TIME: '१५ मिनिटे',
    EXPLORE_ALL: 'सर्व शोधा'
  },
  EXPLORE: {
    AROUND_YOU: 'तुमच्या आजूबाजूला',
    PLACES_NEARBY: 'जवळची ठिकाणे',
    SEARCH_PLACEHOLDER: 'ठिकाणे, अन्न, कार्यक्रम शोधा...',
    ALL_CATEGORIES: 'सर्व श्रेणी',
    FOOD_DINING: 'अन्न आणि जेवण',
    NATURE_PARKS: 'निसर्ग आणि उद्याने',
    SHOPPING: 'खरेदी',
    ARTS_CULTURE: 'कला आणि संस्कृती',
    ENTERTAINMENT: 'मनोरंजन'
  },
  AI_CHAT: {
    THINKING: 'विचार करत आहे...',
    DEFAULT_USER_MSG: 'जवळचे छान कॅफे सुचवा',
    DEFAULT_AI_MSG: 'येथे तुमच्या जवळील काही उत्तम कॅफे आहेत',
    MOCK_RESPONSE: 'ही एक उत्तम योजना वाटते! लवकरच बॅकएंड इंटिग्रेशन हे हाताळेल.',
    HEADER_TITLE: 'तुम्हाला आज काय करायचे आहे?',
    HEADER_SUBTITLE: 'मी तुम्हाला खाण्यासाठी, पिण्यासाठी किंवा फिरण्यासाठी उत्तम ठिकाणे शोधण्यात मदत करू शकतो.',
    PLACEHOLDER: 'काहीही विचारा...',
    DIRECTIONS: 'दिशा',
    ORDER: 'ऑर्डर',
    START_CHAT: 'नवीन संभाषण सुरू करा',
    RECENT_SEARCHES: 'अलीकडील शोध',
    CLEAR_ALL: 'सर्व साफ करा',
    FIND_LOCAL_FOOD: 'स्थानिक अन्न',
    PLAN_EVENING: 'संध्याकाळची योजना',
    HIDDEN_GEMS: 'लपलेली ठिकाणे',
    FAMILY_OUTING: 'कौटुंबिक सहल',
    BUILD_GROCERY: 'किराणा कार्ट तयार करा'
  },
  SAVED: {
    TITLE: 'सेव्ह केलेली ठिकाणे',
    SUBTITLE: 'त्वरित प्रवेशासाठी बुकमार्क केलेले स्पॉट्स.',
    EMPTY_STATE: 'अद्याप कोणतीही सेव्ह केलेली ठिकाणे नाहीत.',
    EMPTY_SUBTITLE: 'तुमची आवडती ठिकाणे येथे सेव्ह करण्यासाठी एक्सप्लोर करणे सुरू करा!'
  },

  TOAST: {
    LOCATION_SUCCESS: 'स्थान यशस्वीरित्या अपडेट केले!',
    LOCATION_ERROR: 'स्थान मिळवता आले नाही. परवानग्या तपासा.',
    ENABLE_LOCATION: 'उत्तम अनुभवासाठी कृपया स्थान सक्षम करा',
    LOCATION_UPDATED: 'स्थान अपडेट केले',
    LOCATION_FAILED: 'स्थान मिळवण्यात अयशस्वी',
    SELECTED: 'निवडले',
    NO_RESTAURANTS: 'स्विगी एमसीपी द्वारे जवळ कोणतेही रेस्टॉरंट सापडले नाही',
    FETCH_FAILED: 'रेस्टॉरंट्स आणण्यात अयशस्वी',
    OPENING_MENU: 'मेनू उघडत आहे'
  },
  SETTINGS: {
    TITLE: 'सेटिंग्ज',
    PREFERRED_RADIUS: 'प्राधान्यकृत त्रिज्या',
    TEMPERATURE_UNITS: 'तापमान युनिट्स',
    CELSIUS: 'सेल्सिअस (°C)',
    FAHRENHEIT: 'फॅरेनहाइट (°F)',
    THEME: 'थीम',
    LIGHT: 'प्रकाश',
    DARK: 'अंधार',
    SYSTEM: 'प्रणाली',
    LANGUAGE: 'भाषा',
    ENGLISH: 'इंग्रजी',
    HINDI: 'हिंदी',
    ODIA: 'ओडिया',
    LOCATION: 'स्थान',
    ALWAYS: 'नेहमी',
    WHILE_USING: 'अॅप वापरताना',
    NEVER: 'कधीही नाही',
    SWIGGY: 'स्विगी',
    CONNECTED: 'जोडले',
    ORDER_HISTORY: 'ऑर्डर इतिहास',
    ABOUT: 'बद्दल',
    PRIVACY_POLICY: 'गोपनीयता धोरण',
    LOGOUT: 'बाहेर पडा',
    LEGAL_DISCLAIMERS: [
      'whtsnyr.me हे एक माहितीपूर्ण अॅप आहे. एआय-व्युत्पन्न सामग्रीसह येथे दर्शविलेली सर्व सामग्री केवळ शैक्षणिक आणि माहितीच्या उद्देशाने प्रदान केली गेली आहे.',
      'whtsnyr.me मधील सामग्रीचे वैयक्तिकरित्या पुनरावलोकन, मंजुरी किंवा पडताळणी केलेली नाही. कृपया त्यावर कारवाई करण्यापूर्वी कोणत्याही स्थानिक मार्गदर्शक तत्त्वांची किंवा नियमांची पुष्टी करा.',
      'whtsnyr.me हे व्यावसायिक निर्णयाला पर्याय नाही. भेट देण्यापूर्वी ठिकाणाचे तपशील, इशारे आणि मार्गदर्शक तत्त्वांचे नेहमी पुनरावलोकन करा.'
    ],
    HELP_SUPPORT: 'मदत आणि समर्थन',
    LOG_OUT: 'बाहेर पडा',
    ACCOUNT: 'खाते',
    EDIT_PROFILE: 'प्रोफाइल संपादित करा',
    PREFERENCES: 'प्राधान्ये',
    NOTIFICATIONS: 'सूचना',
    DARK_MODE: 'डार्क मोड'
  },
  COMMON: {
    COPYRIGHT: 'कॉपीराइट © 2026 whtsnyr.me v1.0.0.',
    REGION: 'OD 19'
  }
};
