export const LABELS = {
  NAVBAR: {
    HOME: 'Home',
    AI: 'AI',
    AI_ASSISTANT: 'AI Assistant',
    EXPLORE: 'Explore',
    SAVED: 'Saved',
    SETTINGS: 'Settings',
    YOU: 'You'
  },
  HOME: {
    GREETING: 'Good Morning,',
    WEATHER_HERO_TITLE: 'Pleasant weather today.',
    WEATHER_HERO_SUBTITLE: 'Great time to explore local cafés.',
    HUMIDITY: 'Humidity',
    GOOD: 'Good',
    SUNNY: 'Sunny',
    KM_H: 'km/h',
    WHAT_TO_DO: 'What do you want to do today?',
    HINT_COFFEE: 'Try "Find a quiet coffee shop"',
    HINT_PARKS: 'Try "Show me parks nearby"',
    FOR_YOU: 'For you',
    RECOMMENDED: 'Recommended based on your activity',
    PLACES_NEARBY: 'Places nearby',
    NEARBY_HIGHLIGHTS: 'Nearby highlights',
    LOCAL_SPECIALITIES: 'Local specialities',
    NEARBY_SUBTITLE: 'Discover spots around your current location',
    SWIGGY_INSTAMART: 'Swiggy Instamart',
    DELIVERY_TIME: '15 mins',
    EXPLORE_ALL: 'Explore all'
  },
  EXPLORE: {
    AROUND_YOU: 'Around you',
    PLACES_NEARBY: 'Places nearby',
    SEARCH_PLACEHOLDER: 'Search places, food, events...',
    ALL_CATEGORIES: 'All Categories',
    FOOD_DINING: 'Food & Dining',
    NATURE_PARKS: 'Nature & Parks',
    SHOPPING: 'Shopping',
    ARTS_CULTURE: 'Arts & Culture',
    ENTERTAINMENT: 'Entertainment'
  },
  AI_CHAT: {
    HEADER_TITLE: 'What do you want to do today?',
    HEADER_SUBTITLE: 'I can help you find the best places to eat, drink, or explore.',
    PLACEHOLDER: 'Ask anything...',
    DIRECTIONS: 'Directions',
    ORDER: 'Order',
    START_CHAT: 'Start a new conversation',
    RECENT_SEARCHES: 'Recent Searches',
    CLEAR_ALL: 'Clear All',
    FIND_LOCAL_FOOD: 'Find famous local food',
    PLAN_EVENING: 'Plan my evening',
    HIDDEN_GEMS: 'Hidden gems nearby',
    FAMILY_OUTING: 'Family outing',
    BUILD_GROCERY: 'Build grocery cart'
  },
  SAVED: {
    TITLE: 'Saved Places',
    SUBTITLE: 'Your bookmarked spots for quick access.',
    EMPTY_STATE: 'No saved places yet.',
    EMPTY_SUBTITLE: 'Start exploring to save your favorite spots here!'
  },
  SETTINGS: {
    TITLE: 'Settings',
    PREFERRED_RADIUS: 'Preferred radius',
    TEMPERATURE_UNITS: 'Temperature units',
    CELSIUS: 'Celsius (°C)',
    FAHRENHEIT: 'Fahrenheit (°F)',
    THEME: 'Theme',
    LIGHT: 'Light',
    DARK: 'Dark',
    SYSTEM: 'System',
    LANGUAGE: 'Language',
    ENGLISH: 'English',
    HINDI: 'Hindi',
    ODIA: 'Odia',
    LOCATION: 'Location',
    ALWAYS: 'Always',
    WHILE_USING: 'While using the app',
    NEVER: 'Never',
    SWIGGY: 'Swiggy',
    CONNECTED: 'Connected',
    ORDER_HISTORY: 'Order history',
    ABOUT: 'About',
    PRIVACY_POLICY: 'Privacy Policy',
    LEGAL_DISCLAIMER_1: 'whtsnyr.me is an informational app. All content shown here, including AI-generated content, is provided for educational and informational purposes only.',
    LEGAL_DISCLAIMER_2: 'Content in whtsnyr.me is not individually reviewed, approved, or verified. Please confirm any local guidelines or regulations before acting on it.',
    LEGAL_DISCLAIMER_3: 'whtsnyr.me is not a replacement for professional judgment. Always review the place details, warnings, and guidelines before visiting.',
    HELP_SUPPORT: 'Help & Support',
    LOG_OUT: 'Log Out',
    ACCOUNT: 'Account',
    EDIT_PROFILE: 'Edit Profile',
    PREFERENCES: 'Preferences',
    NOTIFICATIONS: 'Notifications',
    DARK_MODE: 'Dark Mode'
  },
  ABOUT: {
    TITLE: 'whtsnyr.me',
    HERO_TEXT_1: 'Around',
    HERO_TEXT_2: 'you,',
    HERO_TEXT_3: 'reimagined.',
    BADGE_TEXT: 'EXPLORE • WHTSNYR.ME • EXPLORE • WHTSNYR.ME • EXPLORE • WHTSNYR.ME • ',
    SECTION_1_TITLE: 'Discover.',
    SECTION_1_SUBTITLE: 'Without the noise.',
    SECTION_1_P1: 'A real-time discovery engine with AI-powered insights isolates exactly what you care about. Say goodbye to outdated tourist blogs.',
    SECTION_1_P2_1: 'See ',
    SECTION_1_P2_BOLD: 'curated details',
    SECTION_1_P2_2: ' and get personalized recommendations tailored to your exact vibe for dining, sights, and hidden gems.',
    SECTION_2_TITLE: 'Take the ',
    SECTION_2_TITLE_HIGHLIGHT: 'scenic route.',
    SECTION_2_P1: 'Whether you\'re wandering through a vibrant new city or just taking a stroll around the block, our dynamic routing algorithm maps the most enjoyable path, not just the fastest.',
    SECTION_2_P2_BOLD: 'Step-by-step guidance',
    SECTION_2_P2: ' ensures you never miss a beat. Uncover street art, local cafes, and beautiful parks along the way.',
    WHY_TITLE: 'Why we built this?',
    WHY_TEXT: 'We were tired of sifting through endless, SEO-optimized travel blogs just to find one authentic recommendation. The modern web is noisy, and finding real experiences has become a chore. We built this engine to cut through the clutter and connect you directly with the vibrant, hidden gems around you—instantly.',
    CONTACT_PRE: 'For more info or help, ',
    CONTACT_LINK: 'contact us',
    CONTACT_POST: '.'
  },
  PRIVACY: {
    TITLE: 'Privacy Policy',
    LAST_UPDATED: 'Last updated: July 2026',
    SECTION_1_TITLE: '1. Data Collection',
    SECTION_1_TEXT: 'At whtsnyr.me, we respect your privacy. When you use our app to discover local places, we may collect your rough or precise location data, but only if you explicitly grant us permission. We do not store your location history on our servers.',
    SECTION_2_TITLE: '2. How We Use Your Data',
    SECTION_2_TEXT: 'Your location data is used strictly in real-time to curate the best local restaurants, events, and weather updates around you. If you choose to connect third-party services like Swiggy, we only retrieve your order history locally to personalize your AI assistant\'s recommendations.',
    SECTION_3_TITLE: '3. Data Sharing',
    SECTION_3_TEXT: 'We believe your data is yours. We do not sell your personal information, location, or search history to third-party advertisers or data brokers.',
    SECTION_4_TITLE: '4. Security',
    SECTION_4_TEXT: 'We employ industry-standard encryption to protect any data transmitted between your device and our services. Since most of your personalized data (like saved places and history) is stored locally on your device, you remain in full control.',
    CONTACT: 'Contact Us',
    CONTACT_TEXT: 'If you have any questions about this Privacy Policy, please contact us at privacy@whtsnyr.me.'
  },
  COMMON: {
    COPYRIGHT: 'Copyright © 2026 whtsnyr.me v1.0.0.',
    REGION: 'OD 19'
  }
};
